version: "3.12"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 80000"
    environment:
      PINECONE_API_KEY: ${PINECONE_API_KEY}
    depends_on:
      - meilisearch
      - pinecone

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    command: ["meilisearch"]

  pinecone:
    image: pinecone/pinecone:latest
    environment:
      PINECONE_API_KEY: ${PINECONE_API_KEY}
    ports:
      - "7100:7100"
